import type { Metadata } from "next";
import StoreProvider from "@/redux/provider"
import Header from "./components/Header";

import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="fr" className="h-full">
       <body className="relative h-full flex flex-col">
        <StoreProvider>
          <Header/>
          {children}
        </StoreProvider>
      </body>
    </html>
  );
}
