import type { Metadata } from "next";
import StoreProvider from "@/redux/provider"

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="fr">
       <body className={`flex flex-col gap-8`}>
        <StoreProvider>
          {children}
        </StoreProvider>
      </body>
    </html>
  );
}
